name: Deploy Knoxctl's webpage to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build Hugo Site
      run: hugo --minify

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ID }}
        aws-region: us-east-2

    - name: Deploy to S3
      run: |
        aws s3 sync ./public s3://knoxctl.accuknox.com --delete

